### ISSUE TITLE
Indicator if adblocking is enabled

### ISSUE THREAD

**Issue by rpeter85** [blokadaorg/vpn-beta-tracker#19]
The opening screen of Blokada shows how much ads are blocked, if the VPN is enabled, but doesn't show if the adblocker function is enabled.
It can be turned off and on in the menu, but there's no feedback on the main screen, which would be helpful.

**Comment by balboah** [comment]
Instead of how much is blocked, I think it should be a status like the other "foobar enabled". "Ad-blocking: On". When you expand it, there can be counters of number of blocks

**Comment by kar** [comment]
Counter is very important since we've seen users organically sharing it on social media. Fixed the status showing.
