### ISSUE TITLE
VPN may get stuck in selecting new gateway

### ISSUE THREAD

**Issue by balboah** [blokadaorg/vpn-beta-tracker#37]
### 1

- Active account
- gw 1 was in state ON
- switched to gw 2. Both was ON for a while, but then only gw 2, everything good
- switch out of app, tests connectivity, switch back
- select gw 1 again
- both are marked ON. the "waves" keep spamming a lot, there is no connectivity. Both stays ON
- screen off, phone idle couple of minutes
- open app again, go to sub menu: screen is black, no content (waves keep spamming)

### 2

- turn vpn off through home screen: internet works again
- trun vpn on: submenu works, gw 2 is ON. internet stops working, waves spamming again

**Comment by kar** [comment]
fixed
