### ISSUE TITLE
UI redesing idea

### ISSUE THREAD

**Issue by rpeter85** [blokadaorg/vpn-beta-tracker#41]
The idea is the following:
- The main, opening screen would be on the left, just like now, and would provide information (like now), and maybe the set DNS server as well. In its submenu would be available the VPN gateway, option to activate the VPN, etc, because I'm sure that will be the most used function, so should be easily available.
- The 2nd screen, to the right from the main is for blocking, with the blocked and allowed hosts on the screen and the lists, whitelisted installed and whitelisted system apps in the submenu.
- The third page, on the right side, the Settings: number of filters, available updates, an option to manually update the lists, and in its submenu, all the available settings.

The above layout could help users to access what they use very frequently (VPN), what they want to check easily if they are interested (blocking statistics).

**Comment by kar** [comment]
implemented.
