### ISSUE TITLE
Restore account makes submenu and vpn activate to fail

### ISSUE THREAD

**Issue by balboah** [blokadaorg/vpn-beta-tracker#43]
### 1 

- activate account
- activate gateway
- store the acount id
- reset app and clear data
- restore account id

submenu now becomes black.
home screen vpn cycles on trying to activate vpn (and submenu cycles to become black on each attempt?)

### 2

- switched out/in to app
- was able to turn tunnel to active, but no gateway are active ("config can be improved")
- submenu available
- when trying to activate gateway it doesn't turn on

**Comment by kar** [comment]
- get leases
- send DELETE to each lease
- continnue as normal

**Comment by kar** [comment]
activate cycle is because the app wanted to start vpn without ip addresses or gateway information.
