### ISSUE TITLE
UI change: Deactivating Blokada

### ISSUE THREAD

**Issue by ps100000** [blokadaorg/vpn-beta-tracker#46]
The current way of swiping down on the submenuebar is not very intuitive.
I think it would be better to just deactivate the app if the user deactivates ad blocking and vpn or clicks the shield in the left upper corner

**Comment by PrintableCharacter** [comment]
Yes please. That would be great.

**Comment by kar** [comment]
There 'turn off' in main screen. Will make blokada Logo tappable as well.
