### ISSUE TITLE
Blokada (nearly) unresponsive once custom tab content is being opened and left again

### ISSUE THREAD

**Issue by PrintableCharacter** [blokadaorg/vpn-beta-tracker#53]
Steps to reproduce:
1. Go to the DNS Section of the app
2. open a DNS Drop down menu
3. Wait until the website is loaded
4. Leave the custom tab by using the lower "back" key of your smartphone
5. Notice that all options and drop down menus are unresponsive Exept the big lower advanced options "lever" (I've no clue how to call this. The thing that you can swipe up)

**Comment by kar** [comment]
can't reproduce, could you send me a video on priv?

**Comment by PrintableCharacter** [comment]
I guess I can close this now xD
